### ISSUE TITLE
About negative samples in queue

### ISSUE THREAD

**Issue by BZboys** [XLearning-SCU/2022-CVPR-AirNet#1]
Thanks for your great code. I'm a little confused about the negative sample setting. There are five tasks: {'denoise_15': 0, 'denoise_25': 1, 'denoise_50': 2, 'derain': 3, 'dehaze': 4}, and the queue size equals to 256*3. So, how do you ensure that the queue is filled with negative samples that are different from the current degradation?

**Comment by XLearning-SCU** [comment]
Thanks for you valuable suggestions, we do not specially pick out the false negative pairs in the queue, for they are widely existed in the contrastive learning. In the next version, we will try to re-train our model by removing the false negative pairs.

**Comment by XLearning-SCU** [comment]
同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论
