### ISSUE TITLE
about Waterloo Exploration Database

### ISSUE THREAD

**Issue by chensming** [XLearning-SCU/2022-CVPR-AirNet#12]
Thanks for the great research on multi degradation restoration. But when I tried to train the networks, I found the link of Waterloo Exploration Database did not work (http://ivc.uwaterloo.ca/database/WaterlooExploration/exploration_database_and_code.rar). Could you submit it or provide a download link?

**Comment by ScarletBlaze** [comment]
I also have this problem and can't find the corresponding dataset. Have you found the download resource for the WED dataset yet?

**Comment by chensming** [comment]
> Have you found the download resource for the WED dataset yet?

Not yet, bro. Have you found it?
