### ISSUE TITLE
About combined degradations

### ISSUE THREAD

**Issue by Kaiwen-Zhu** [XLearning-SCU/2022-CVPR-AirNet#17]
Thanks for your excellent work! Also, may I ask if you've tried training AirNet on images with multiple degradations that simultaneously present in one image? Do you think this is feasible for AirNet? I believe such topics are worth studying.

**Comment by XLearning-SCU** [comment]
Many thanks for your attention to our work. In fact, I have not trained AirNet on combined degradations yet, I guess it will be feasible and worthy to investigating. Besides, considering the AirNet could process the combined degradation in a recurrent manner (which means you could put the combined degradations to the network, and put the output to the network again), you could set it as the baseline to observe the performance improvement.
