### ISSUE TITLE
Reduce sigma lower than 15?

### ISSUE THREAD

**Issue by AIisCool** [XLearning-SCU/2022-CVPR-AirNet#2]
Good results! But is it possible to go lower than 15?

**Comment by XLearning-SCU** [comment]
Yes, in the supplementary material we test our pre-trained model on BSD68 with sigma=10, and AirNet achieves 35.60dB in PSNR and 0.9476dB in SSIM. If you want to train AirNet with sigma lower than 15, you could modify the code in utils/dataset_utils.py and train your model.
