### ISSUE TITLE
problem of "conda env create -f airnet.yaml"

### ISSUE THREAD

**Issue by LouisCodingMachine** [XLearning-SCU/2022-CVPR-AirNet#20]
![image](https://github.com/XLearning-SCU/2022-CVPR-AirNet/assets/105021482/4cbfc511-4b16-47df-bd04-bdbc8757fc7c)

Like above image, this command don't work in Ubuntu 20.04.6 LTS

**Comment by XLearning-SCU** [comment]
Many thanks for your attention to our work. You could refer to the following pages to solve this problem, it seems to be caused by conda:
https://blog.csdn.net/m0_67839004/article/details/137934614
