### ISSUE TITLE
denoising dataset

### ISSUE THREAD

**Issue by dlwogns410** [XLearning-SCU/2022-CVPR-AirNet#21]
The WED data of the denoising dataset you uploaded in the readme is currently NOT FOUND. Is there another way to download this dataset? Also, is the denoising dataset you uploaded the dataset that currently has noise added? If not, can you tell me how to add noise?
![NOT FOUND](https://github.com/user-attachments/assets/e0c5b718-bd64-4e47-b241-22ef16a46187)

**Comment by XLearning-SCU** [comment]
Thanks for your attention to our work. We have modified the download links of WED, you could also download the dataset from the following links:
http://ivc.uwaterloo.ca/database/WaterlooExploration/exploration_database_and_code.rar
The original images in the WED do not contain noise, by following other denoising baselines, we added noise by ourselves, which could be referred to:
https://github.com/XLearning-SCU/2022-CVPR-AirNet/blob/bedea82f7f7a71f135bcc026fd02ea9f2feaa710/utils/degradation_utils.py#L21C1
