### ISSUE TITLE
Use both custom clean photos and degraded photos?

### ISSUE THREAD

**Issue by corranmac** [XLearning-SCU/2022-CVPR-AirNet#3]
Hi there, your work looks fantastic.

I was wondering if theres a way to train the model on a custom folder of clean and noisy photos?

Thanks!

**Comment by XLearning-SCU** [comment]
同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论

**Comment by XLearning-SCU** [comment]
Thanks for your attention.
If you have paired clean and noisy images, you could modify the code of TrainDataset in the utils/dataset_utils.py to train the model on a custom folder. If not, it may be hard to train the model.
