### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 123456789-qwer** [XLearning-SCU/2022-CVPR-AirNet#5]
Thank you for your work!
ModuleNotFoundError: No module named 'mmcv._ext' is displayed after installation according to the YAML file.
how can I solve it?

**Comment by XLearning-SCU** [comment]
同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论

**Comment by 123456789-qwer** [comment]
> 同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论

？

**Comment by XLearning-SCU** [comment]
Thanks for you attention.
To install mmcv._ext, it is recommend to use command "pip install mmcv-full" instead of "pip install mmcv". The second command will not install CUDA ops.
