### ISSUE TITLE
About the all-in-one training details

### ISSUE THREAD

**Issue by huang-hz** [XLearning-SCU/2022-CVPR-AirNet#7]
Hi, I am confusing about the "In other words, AirNet under AIO is the model trained on the collection of all the datasets that 
consists of three corruptions (i.e., noise, rain, and haze) with different degradation levels (i.e., σ = 15, 25, 50)."
    Is it true that the three corruptions datasets is mixed up in the trainning procedure ？

**Comment by ZihanGao777** [comment]
Mr.Huang，I have the same confusion with you.Have you find out the answer?

**Comment by XLearning-SCU** [comment]
I am sorry for replying so late. In AIO setting, we mixed up all of these three corruption datasets for training. For denoising dataset, we random add the gaussian noise (sigma=15, 25 or 50) to the input clean image.

> Mr.Huang，I have the same confusion with you.Have you find out the answer?

**Comment by ZihanGao777** [comment]
I am glad to receive your reply.Thank you.

在 2024-07-10 21:51:09，"XLearning Group" ***@***.***> 写道：


I am sorry for replying so late. In AIO setting, we mixed up all of these three corruption datasets for training. For denoising dataset, we random add the gaussian noise (sigma=15, 25 or 50) to the input clean image.

Mr.Huang，I have the same confusion with you.Have you find out the answer?
